import { ToggleMode } from "@/components/ToggleMode";
import "./globals.css";
import { Raleway } from "next/font/google";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Page Speed Stats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black bg-slate-200`}>
        <main className="containerFluid mt-8">
          <div className="my-8 flex justify-between items-center">
            <img
              width={25}
              className="dark:invert"
              src="/icons/icon-github.svg"
              alt="Github"
            />
            <p className=" font-bold text-2xl  dark:text-white">PageSpeed.sh</p>
            <ToggleMode />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
